# Generated by Django 6.0.1 on 2026-01-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.CharField(max_length=255)),
                ('customer_mobile', models.CharField(max_length=255)),
                ('customer_password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ecomm_customers',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_created', models.CharField(max_length=255)),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_email', models.CharField(max_length=255)),
                ('partner_mobile', models.CharField(max_length=255)),
                ('partner_password', models.CharField(max_length=255)),
                ('partner_address', models.CharField(max_length=255)),
                ('partner_state', models.CharField(max_length=255)),
                ('partner_city', models.CharField(max_length=255)),
                ('partner_pincode', models.BigIntegerField()),
                ('partner_status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ecomm_partners',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_by', models.BigIntegerField()),
                ('product_created', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField()),
                ('product_cover_image', models.ImageField(upload_to='products/')),
                ('product_status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ecomm_products',
            },
        ),
    ]
