# Generated by Django 6.0.1 on 2026-05-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_orderitems_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
